title: "I'm thinking about stuff"
email: kettle.corn.with.a.Q.U@gmail.com
description: >-
  Do you ever think about stuff? Because I sure do.
baseurl: ""
url: "https://kettlecornwitha-QU.github.io/Im-thinking/"
theme: minimal
markdown: kramdown
include:
  - papers
kramdown:
    math_engine: mathjax
    input: GFM
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
sass:
  style: compressed
