title: "I'm thinking about stuff"
email: kettle.corn.with.a.Q.U@gmail.com
description: >-
  Do you ever think about stuff? Because I do.
baseurl: "/Im-thinking"
url: "https://kettlecornwitha-QU.github.io"
theme: minimal
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
paginate: 5
