title: "I'm thinking about stuff"
email: kettle.corn.with.a.Q.U@gmail.com
description: >-
  Do you ever think about stuff? Because I sure do.
url: "https://kettlecornwitha-QU.github.io"
#baseurl: "/Im-thinking"
theme: jekyll-theme-minimal
markdown: kramdown
include:
  - papers
kramdown:
    math_engine: mathjax
    input: GFM
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
  style: compressed
